apiVersion: v1
kind: Service
metadata:
  name: cloud-movie-solution-service
spec:
  ports:
    - name: http
      port: 8090
      targetPort: 8090
  selector:
    app: cloud-movie-solution
  type: NodePort